apiVersion: v1
kind: Pod
metadata: 
  name: pod1
spec: 
  containers:
  - name: nginx-chandra
    image: nginx
    ports:
    - containerPort: 8080
  name: pod2
spec: 
  containers:
  - name: watcher
    image: afakharany/watcher
    ports:
    - containerPort: 8080
    

    
