apiVersion: v1
kind: pod
metadata:
  name: pod3
  labels: 
    app: helloworld
    env: dev
    application: ui
spec:
  continers:
  - name: k8s-demo
    image: arjunachari12/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
