apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  ports:
  -  port: 31001
     nodePort: 31002
     targetPort: nodejs-port
     protocol: TCP
   selector:
     app: helloworld
   type: NodePort
